;;; Put this function into your .emacs files
;;; Instructions found here:
;;; https://emacs.stackexchange.com/questions/70/how-to-save-a-keyboard-macro-as-a-lisp-function

;;; Open db.xml side by side with the calibration output table
;;; generated by the visualC++ code. Then call
;;; M-x gen_db_xml with your cursor on id_1 of 
;;; the db.xml and the other cursor on id 1 of
;;; the table output
(fset 'gen_db_xml
   (lambda (&optional arg) "Keyboard macro." (interactive "p") (kmacro-exec-ring-item (quote ([5 right 24 111 down 19 58 right 67108896 5 134217847 right 24 111 1 right 19 118 101 114 116 C-right right right 25 67108896 19 60 left 23 up up right 19 62 right left 24 111 19 58 right 67108896 5 134217847 right 24 111 25 67108896 19 60 left 23 5 down down 1 19 95 62 right left 67108896 M-right left left 19 60 left 23 24 111 19 58 right 67108896 5 134217847 right 24 111 25 5 right 19 95 62 right left 67108896 19 60 left 23 24 111 19 58 right 67108896 5 134217847 right 24 111 25 5 right 19 62 right left 67108896 19 60 left 23 24 111 19 58 right 67108896 5 134217847 right 24 111 25 5 right 19 95 62 right left 67108896 19 60 left 23 24 111 19 58 right 67108896 5 134217847 right 24 111 25 5 right 24 111 19 58 right 67108896 5 134217847 right 24 111 19 62 right left 25 67108896 19 60 23 left left 5 60 backspace 1 19 62 right left 25 19 60 left 18 62 right 25 67108896 19 60 left 23 5 right 24 111 19 58 right 67108896 5 134217847 24 111 19 62 right backspace 25 5 right 24 111 right 19 58 right 67108896 5 134217847 right 24 111 19 95 62 right backspace 25 18 62 right 25 67108896 19 60 left 23 5 right 19 105 100 19 19 1 24 111 down down down 24 111] 0 "%d")) arg)))
